[project]
name = "call-me-maybe"
version = "0.1.0"
description = "LLM SDK for local model inference"
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "pydantic",
    "accelerate",
    "llm-sdk"
]

[dependency-groups]
dev = [
    "flake8",
    "mypy",
    "pytest",
]

[tool.uv]
package = false

[tool.uv.workspace]
members = [
    "llm_sdk",
]

[tool.uv.sources]
llm-sdk = { workspace = true, editable = true }